
CREATE DATABASE vnode2 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode2.* TO '2roor'@'%';

CREATE DATABASE vnode3 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode3.* TO '2roor'@'%';

CREATE DATABASE vnode4 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode4.* TO '2roor'@'%';

CREATE DATABASE vnode5 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode5.* TO '2roor'@'%';

CREATE DATABASE vnode6 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode6.* TO '2roor'@'%';

CREATE DATABASE vnode7 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode7.* TO '2roor'@'%';

CREATE DATABASE vnode8 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode8.* TO '2roor'@'%';

CREATE DATABASE vnode9 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode9.* TO '2roor'@'%';

CREATE DATABASE vnode10 CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON vnode10.* TO '2roor'@'%';
