version: '3'
services:
  redis:
    image: 'redis:latest'
    
    restart: always
    networks:
      - main
    ports:
      - 6379:6379
    volumes:
      - ./external/redis:/data

  mysql:
    image: mysql:5.7.32
    container_name: db
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    # Change this to your local path
    volumes:
      - ./external/mysql:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 3000M
    restart: always
    ports:
      - 8183:80

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./external/ipfs:/data
    ports:
      - '4001:4001'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
      - '127.0.0.1:5001:5001'

networks:
  main:
    driver: bridge
