export enum VIDEO_NOTIFICATION_ACCESS_TYPE {
  PUSH_CHAT = 'PUSH_CHAT'
}

export enum VIDEO_CALL_STATUS {
  UNINITIALIZED,
  INITIALIZED,
  RECEIVED,
  CONNECTED,
  DISCONNECTED,
  RETRY_INITIALIZED,
  RETRY_RECEIVED
}
