# todo DATABASE_URL - remove after k8s nodes -> docker-compose
version: '3'
services:

  anode1:
    image: anode-main
    container_name: anode1
    networks:
      push-shared-network:
        aliases:
          - anode1.local
    environment:
      DB_NAME: anode1
      PORT: 5001
    env_file:
      - common.env
      - a-specific.env
    ports:
      - "5001:5001"
    entrypoint: ['sh', '/entrypoint.sh']
    volumes:
      - ./a1:/config
      - ./a1/log:/log
      - ./_abi/:/config/abi/


networks:
  push-shared-network:
    external: true