version: '3'
services:

  anode1:
    image: anode-main
    container_name: anode1
    ports:
      - "2001:2001"
    networks:
      push-shared-network:
        aliases:
          - anode1.local
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.local:5432/anode1
      CONFIG_DIR: /config
      LOG_DIR: /log
      VALIDATOR_CONTRACT_ADDRESS: ${VALIDATOR_CONTRACT_ADDRESS}
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
      ANODE_PORT: 2001
    volumes:
      - ./a1:/config
      - ./a1/log:/log

networks:
  push-shared-network:
    external: true