version: '3'
services:

  redis:
    image: 'redis:latest'
    container_name: redis1
    restart: always
    networks:
      push-dev-network:
        aliases:
          - redis.local
    ports:
      - ${EXTERNAL_REDIS_PORT}:6379
    volumes:
      - ./external/redis:/data

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin1
#    depends_on:
#      - mysql
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#      UPLOAD_LIMIT: 3000M
#    restart: always
#    ports:
#      - 8183:80
#    networks:
#      push-shared-network:
#        aliases:
#          - phpmyadmin.local


  # for V nodes we use mysql
  mysql:
    image: mysql:8.0
    container_name: mysql1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${EXTERNAL_DB_PORT}:3306'
    volumes:
      - ./external/mysql:/var/lib/mysql/
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      push-dev-network:
        aliases:
          - mysql.local

  # for snodes and a nodes we use postgres
  postgres:
    image: postgres:15.1
    container_name: postgres1
    restart: always
    environment:
      - POSTGRES_DB=snode1
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - '${EXTERNAL_PG_PORT}:5432'
    volumes:
      - ./external/postgresql:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d/
    networks:
      push-dev-network:
        aliases:
          - postgres.local

networks:
  push-dev-network:
    external: true