version: '3'
services:

  hardhat1:
    image: hardhat-main
    container_name: hardhat1
    networks:
      push-dev-network:
        aliases:
          - hardhat.local
    ports:
      - "8545:8545"
    restart: always
    environment:
      SEPOLIA_RPC_URL: 11
      SEPOLIA_PRIVATE_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      VNODE_COUNT: 3
      SNODE_COUNT: 1
      ANODE_COUNT: 1

networks:
  push-dev-network:
    external: true