version: '3'
services:

  hardhat1:
    image: hardhat-main
    container_name: hardhat1
    networks:
      push-dev-network:
        aliases:
          - hardhat.local
    ports:
      - "8545:8545"
    restart: always
    environment:
      SEPOLIA_RPC_URL: 11
      SEPOLIA_PRIVATE_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      # if you edit these values for local env, the setup is the following:
      # remove everything: ./cleanup.sh
      # uncomment N number of records in v.yml ; s.yml; a.yml which matches the values above
      # re-create everything: ./setup.sh
      VNODE_COUNT: 3 # max 10
      SNODE_COUNT: 1 # max 8
      ANODE_COUNT: 1 # max 5


networks:
  push-dev-network:
    external: true