version: '3'
services:

  phardhat:
    image: hardhat-main
    container_name: hardhat
    networks:
      push-dev-network:
        aliases:
          - hardhat.local
    ports:
      - "8545:8545"
    restart: always
    environment:
      SEPOLIA_RPC_URL: 11
      SEPOLIA_PRIVATE_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

networks:
  push-dev-network:
    external: true