version: '3'
services:

  snode1:
    image: snode-main
    container_name: snode1
    networks:
      push-shared-network:
        aliases:
          - snode1.local
    environment:
      PG_NAME: snode1
      PG_USER: ${POSTGRES_USER}
      PG_PASS: ${POSTGRES_PASSWORD}
      PG_HOST: postgres.local
      DB_NAME: snode1
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: 3001
      CONFIG_DIR: /config
      LOG_DIR: /log
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
      VALIDATOR_PUSH_TOKEN_ADDRESS: ${VALIDATOR_PUSH_TOKEN_ADDRESS}
      VALIDATOR_CONTRACT_ADDRESS: ${VALIDATOR_CONTRACT_ADDRESS}
      STORAGE_CONTRACT_ADDRESS: ${STORAGE_CONTRACT_ADDRESS}
    ports:
      - "3001:3001"
    volumes:
      - ./s1:/config
      - ./s1/log:/log

  snode2:
    image: snode-main
    container_name: snode2
    networks:
      push-shared-network:
        aliases:
          - snode2.local
    environment:
      PG_NAME: snode2
      PG_USER: ${POSTGRES_USER}
      PG_PASS: ${POSTGRES_PASSWORD}
      PG_HOST: postgres.local
      DB_NAME: snode2
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: 3002
      CONFIG_DIR: /config
      LOG_DIR: /log
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
      VALIDATOR_PUSH_TOKEN_ADDRESS: ${VALIDATOR_PUSH_TOKEN_ADDRESS}
      VALIDATOR_CONTRACT_ADDRESS: ${VALIDATOR_CONTRACT_ADDRESS}
      STORAGE_CONTRACT_ADDRESS: ${STORAGE_CONTRACT_ADDRESS}
    ports:
      - "3002:3002"
    volumes:
      - ./s2:/config
      - ./s2/log:/log

networks:
  push-shared-network:
    external: true