version: '3'
services:


  snode1:
    image: snode-main
    container_name: snode1
    networks:
      push-shared-network:
        aliases:
          - snode1.local
    environment:
      DB_NAME: snode1
      PORT: 3001
    env_file:
      - common.env
      - s.env
    ports:
      - "3001:3001"
    volumes:
      - ./s1:/config
      - ./s1/log:/log
      - ./_abi/:/config/abi/


  snode2:
    image: snode-main
    container_name: snode2
    networks:
      push-shared-network:
        aliases:
          - snode2.local
    environment:
      DB_NAME: snode2
      PORT: 3002
    env_file:
      - common.env
      - s.env
    ports:
      - "3002:3002"
    volumes:
      - ./s2:/config
      - ./s2/log:/log
      - ./_abi/:/config/abi/


  snode3:
    image: snode-main
    container_name: snode3
    networks:
      push-shared-network:
        aliases:
          - snode3.local
    environment:
      DB_NAME: snode3
      PORT: 3003
    env_file:
      - common.env
      - s.env
    ports:
      - "3003:3003"
    volumes:
      - ./s3:/config
      - ./s3/log:/log
      - ./_abi/:/config/abi/


  snode4:
    image: snode-main
    container_name: snode4
    networks:
      push-shared-network:
        aliases:
          - snode4.local
    environment:
      DB_NAME: snode4
      PORT: 3004
    env_file:
      - common.env
      - s.env
    ports:
      - "3004:3004"
    volumes:
      - ./s4:/config
      - ./s4/log:/log
      - ./_abi/:/config/abi/


  snode5:
    image: snode-main
    container_name: snode5
    networks:
      push-shared-network:
        aliases:
          - snode5.local
    environment:
      DB_NAME: snode5
      PORT: 3005
    env_file:
      - common.env
      - s.env
    ports:
      - "3005:3005"
    volumes:
      - ./s5:/config
      - ./s5/log:/log
      - ./_abi/:/config/abi/


  snode6:
    image: snode-main
    container_name: snode6
    networks:
      push-shared-network:
        aliases:
          - snode6.local
    environment:
      DB_NAME: snode6
      PORT: 3006
    env_file:
      - common.env
      - s.env
    ports:
      - "3006:3006"
    volumes:
      - ./s6:/config
      - ./s6/log:/log
      - ./_abi/:/config/abi/


  snode7:
    image: snode-main
    container_name: snode7
    networks:
      push-shared-network:
        aliases:
          - snode7.local
    environment:
      DB_NAME: snode7
      PORT: 3007
    env_file:
      - common.env
      - s.env
    ports:
      - "3007:3007"
    volumes:
      - ./s7:/config
      - ./s7/log:/log
      - ./_abi/:/config/abi/


  snode8:
    image: snode-main
    container_name: snode8
    networks:
      push-shared-network:
        aliases:
          - snode8.local
    environment:
      DB_NAME: snode8
      PORT: 3008
    env_file:
      - common.env
      - s.env
    ports:
      - "3008:3008"
    volumes:
      - ./s8:/config
      - ./s8/log:/log
      - ./_abi/:/config/abi/


networks:
  push-shared-network:
    external: true