version: '3'
services:

  vnode1:
    image: vnode-main
    container_name: vnode1
    networks:
      push-dev-network:
        aliases:
          - vnode1.local
    environment:
      DB_NAME: vnode1
      PORT: 4001
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4001:4001"
    volumes:
      - ./v1:/config
      - ./v1/log:/log
      - ./_abi/:/config/abi/


  vnode2:
    image: vnode-main
    container_name: vnode2
    networks:
      push-dev-network:
        aliases:
          - vnode2.local
    environment:
      DB_NAME: vnode2
      PORT: 4002
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4002:4002"
    volumes:
      - ./v2:/config
      - ./v2/log:/log
      - ./_abi/:/config/abi/


  vnode3:
    image: vnode-main
    container_name: vnode3
    networks:
      push-dev-network:
        aliases:
          - vnode3.local
    environment:
      DB_NAME: vnode3
      PORT: 4003
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4003:4003"
    volumes:
      - ./v3:/config
      - ./v3/log:/log
      - ./_abi/:/config/abi/


  vnode4:
    image: vnode-main
    container_name: vnode4
    networks:
      push-dev-network:
        aliases:
          - vnode4.local
    environment:
      DB_NAME: vnode4
      PORT: 4004
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4004:4004"
    volumes:
      - ./v4:/config
      - ./v4/log:/log
      - ./_abi/:/config/abi/

  vnode5:
    image: vnode-main
    container_name: vnode5
    networks:
      push-dev-network:
        aliases:
          - vnode5.local
    environment:
      DB_NAME: vnode5
      PORT: 4005
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4005:4005"
    volumes:
      - ./v5:/config
      - ./v5/log:/log
      - ./_abi/:/config/abi/

  vnode6:
    image: vnode-main
    container_name: vnode6
    networks:
      push-dev-network:
        aliases:
          - vnode6.local
    environment:
      DB_NAME: vnode6
      PORT: 4006
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4006:4006"
    volumes:
      - ./v6:/config
      - ./v6/log:/log
      - ./_abi/:/config/abi/

  vnode7:
    image: vnode-main
    container_name: vnode7
    networks:
      push-dev-network:
        aliases:
          - vnode7.local
    environment:
      DB_NAME: vnode7
      PORT: 4007
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4007:4007"
    volumes:
      - ./v7:/config
      - ./v7/log:/log
      - ./_abi/:/config/abi/

  vnode8:
    image: vnode-main
    container_name: vnode8
    networks:
      push-dev-network:
        aliases:
          - vnode8.local
    environment:
      DB_NAME: vnode8
      PORT: 4008
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4008:4008"
    volumes:
      - ./v8:/config
      - ./v8/log:/log
      - ./_abi/:/config/abi/

  vnode9:
    image: vnode-main
    container_name: vnode9
    networks:
      push-dev-network:
        aliases:
          - vnode9.local
    environment:
      DB_NAME: vnode9
      PORT: 4009
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4009:4009"
    volumes:
      - ./v9:/config
      - ./v9/log:/log
      - ./_abi/:/config/abi/

  vnode10:
    image: vnode-main
    container_name: vnode10
    networks:
      push-dev-network:
        aliases:
          - vnode10.local
    environment:
      DB_NAME: vnode10
      PORT: 4010
    env_file:
      - common.env
      - v-specific.env
    ports:
      - "4010:4010"
    volumes:
      - ./v10:/config
      - ./v10/log:/log
      - ./_abi/:/config/abi/



networks:
  push-dev-network:
    external: true