version: '3'
services:

  vnode1:
    image: vnode-main
    container_name: vnode1
    networks:
      push-shared-network:
        aliases:
          - vnode1.local
    environment:
      DB_NAME: vnode1
      PORT: 4001
      CONFIG_DIR: /config
      LOG_DIR: /log
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
    ports:
      - "4001:4001"
    volumes:
      - ./v1:/config
      - ./v1/log:/log


  vnode2:
    image: vnode-main
    container_name: vnode2
    networks:
      push-shared-network:
        aliases:
          - vnode2.local
    environment:
      DB_NAME: vnode2
      PORT: 4002
      CONFIG_DIR: /config
      LOG_DIR: /log
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
    ports:
      - "4002:4002"
    volumes:
      - ./v2:/config
      - ./v2/log:/log


  vnode3:
    image: vnode-main
    container_name: vnode3
    networks:
      push-shared-network:
        aliases:
          - vnode3.local
    environment:
      DB_NAME: vnode3
      PORT: 4003
      CONFIG_DIR: /config
      LOG_DIR: /log
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
    ports:
      - "4003:4003"
    volumes:
      - ./v3:/config
      - ./v3/log:/log


  vnode4:
    image: vnode-main
    container_name: vnode4
    networks:
      push-shared-network:
        aliases:
          - vnode4.local
    environment:
      DB_NAME: vnode4
      PORT: 4004
      CONFIG_DIR: /config
      LOG_DIR: /log
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
    ports:
      - "4004:4004"
    volumes:
      - ./v4:/config
      - ./v4/log:/log

  vnode5:
    image: vnode-main
    container_name: vnode5
    networks:
      push-shared-network:
        aliases:
          - vnode5.local
    environment:
      DB_NAME: vnode5
      PORT: 4005
      CONFIG_DIR: /config
      LOG_DIR: /log
      DB_HOST: mysql.local
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_URL: redis://redis.local:6379
      VALIDATOR_RPC_ENDPOINT: ${VALIDATOR_RPC_ENDPOINT}
      VALIDATOR_RPC_NETWORK: ${VALIDATOR_RPC_NETWORK}
    ports:
      - "4005:4005"
    volumes:
      - ./v5:/config
      - ./v5/log:/log


networks:
  push-shared-network:
    external: true