version: '3'
services:

  mon1:
    image: docker:cli
    network_mode: none
    cap_drop:
      - ALL
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 60; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done" ]
    restart: unless-stopped


  vnode1:
    image: vnode-main
    container_name: vnode1
    networks:
      push-dev-network:
        aliases:
          - vnode1.local
    environment:
      DB_NAME: vnode1
      PORT: 4001
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4001:4001"
    volumes:
      - ./v1:/config
      - ./v1/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4001/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none


  vnode2:
    image: vnode-main
    container_name: vnode2
    networks:
      push-dev-network:
        aliases:
          - vnode2.local
    environment:
      DB_NAME: vnode2
      PORT: 4002
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4002:4002"
    volumes:
      - ./v2:/config
      - ./v2/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4002/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode3:
    image: vnode-main
    container_name: vnode3
    networks:
      push-dev-network:
        aliases:
          - vnode3.local
    environment:
      DB_NAME: vnode3
      PORT: 4003
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4003:4003"
    volumes:
      - ./v3:/config
      - ./v3/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4003/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode4:
    image: vnode-main
    container_name: vnode4
    networks:
      push-dev-network:
        aliases:
          - vnode4.local
    environment:
      DB_NAME: vnode4
      PORT: 4004
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4004:4004"
    volumes:
      - ./v4:/config
      - ./v4/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4004/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode5:
    image: vnode-main
    container_name: vnode5
    networks:
      push-dev-network:
        aliases:
          - vnode5.local
    environment:
      DB_NAME: vnode5
      PORT: 4005
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4005:4005"
    volumes:
      - ./v5:/config
      - ./v5/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4005/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode6:
    image: vnode-main
    container_name: vnode6
    networks:
      push-dev-network:
        aliases:
          - vnode6.local
    environment:
      DB_NAME: vnode6
      PORT: 4006
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4006:4006"
    volumes:
      - ./v6:/config
      - ./v6/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4006/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode7:
    image: vnode-main
    container_name: vnode7
    networks:
      push-dev-network:
        aliases:
          - vnode7.local
    environment:
      DB_NAME: vnode7
      PORT: 4007
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4007:4007"
    volumes:
      - ./v7:/config
      - ./v7/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4007/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode8:
    image: vnode-main
    container_name: vnode8
    networks:
      push-dev-network:
        aliases:
          - vnode8.local
    environment:
      DB_NAME: vnode8
      PORT: 4008
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4008:4008"
    volumes:
      - ./v8:/config
      - ./v8/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4008/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode9:
    image: vnode-main
    container_name: vnode9
    networks:
      push-dev-network:
        aliases:
          - vnode9.local
    environment:
      DB_NAME: vnode9
      PORT: 4009
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4009:4009"
    volumes:
      - ./v9:/config
      - ./v9/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4009/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none

  vnode10:
    image: vnode-main
    container_name: vnode10
    networks:
      push-dev-network:
        aliases:
          - vnode10.local
    environment:
      DB_NAME: vnode10
      PORT: 4010
    env_file:
      - .env
      - common.env
      - v-specific.env
    ports:
      - "4010:4010"
    volumes:
      - ./v10:/config
      - ./v10/log:/log
      - ./_abi/:/config/abi/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4010/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    logging:
      driver: none



networks:
  push-dev-network:
    external: true